# -*- coding: utf-8 -*-
"""Assignment-15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lZMfFAvfzAvjzTGpgONpW4jxw0uZXfqY
"""

import numpy as np
import cvxpy as cp

P = np.array([[0,1],[1,0]])
q = np.array([3, 0])
x = cp.Variable(2)
V = np.array([[9,0],[0,16]])
u = np.array([0,0])
constraint = [cp.quad_form(x,V) + u.T@x -144 <= 0]
objective = cp.Maximize(cp.quad_form(x,P)+ q.T @ x)
prob = cp.Problem(objective, constraint)
prob.solve()
print(x.value)